### ISSUE TITLE
During diagram generating, some remote connection doesn't work with 

### ISSUE THREAD

**Issue by pillsilly** [immament/vscode-ngrx-uml#10]
As title 
And log as below:
```
ngrx-uml diagram --baseDir=./
Starting...
Use ts-config file: ./tsconfig.json
getMember - unknown node kind PropertyAssignment
getMember - unknown node kind PropertyAssignment
getMember - unknown node kind PropertyAssignment
Items converted
Items rendered
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 104.31.70.56:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
Emitted 'error' event on ClientRequest instance at:
    at Socket.socketErrorListener (_http_client.js:428:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.31.70.56',
  port: 80
}
```

**Comment by immament** [comment]
Extension use http://www.plantuml.com/plantuml/ to generate images from plant-uml files.

If you interested i can add  possibility to configure a different address of render server in extension settings. 
For example local render server http://www.graphviz.org/download/

**Comment by pillsilly** [comment]
> Extension use http://www.plantuml.com/plantuml/ to generate images from plant-uml files.
> 
> If you interested i can add possibility to configure a different address of render server in extension settings.
> For example local render server http://www.graphviz.org/download/

yes that'd be wonderful.

and for people who already got plantuml(and it's plugin) installed I think it's possible to just provide the text of the plantuml file instead (e.g immediately opened in the editor so that the user can naturally see it gets rendered.)
such that they(me in fact 😉 ) can even skip configuring local rendering server for  "vscode-ngrx-uml"
